apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: mongoapi
  name: mongoapi
spec:
  type: NodePort
  ports:
  - name: "port"
    port: 8001
    targetPort: 8000
  selector:
    io.kompose.service: mongoapi
status:
  loadBalancer: {}
