apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: qos
  name: qos
spec:
  selector:
    matchLabels:
      io.kompose.service: qos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: qos
    spec:
      containers:
      - image: 192.168.101.76:5000/loadBalancer
        name: loadBalancer
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
