apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  selector:
    matchLabels:
      io.kompose.service: registry
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: registry
    spec:
      containers:
      - image: registry
        name: registry
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-claim0
      restartPolicy: Always
      volumes:
      - name: registry-claim0
        hostPath:
          path: /mnt/public/registry
status: {}
