apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: registry
  name: registry
spec:
  type: NodePort
  ports:
  - name: "8000"
    port: 8000
    targetPort: 5000
  selector:
    io.kompose.service: registry
status:
  loadBalancer: {}
