apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: internaldb
  name: internaldb
spec:
  ports:
  - name: "serviceport"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: internaldb
status:
  loadBalancer: {}
