apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: lam
  name: lam
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    io.kompose.service: lam
status:
  loadBalancer: {}
