apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: monitor
  name: monitor
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8080
  selector:
    io.kompose.service: monitor
status:
  loadBalancer: {}
