apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: producer
  name: producer
spec:
  selector:
    matchLabels:
      io.kompose.service: producer
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../dockerenv/docker-compose.yml
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: producer
    spec:
      containers:
      - image: producer
        name: producer
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /received/
          name: producer-claim0
      restartPolicy: Always
      volumes:
      - name: producer-claim0
        persistentVolumeClaim:
          claimName: producer-claim0
status: {}
