version: '2'
services:
  ldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    volumes:
      - ./ldap/dbfiles:/var/lib/ldap
      - ./ldap/dbconfig:/var/lib/slapd.d
    environment:
      LDAP_ADMIN_PASSWORD: toor

  lam:
    image: ldapaccountmanager/lam:stable
    ports:
      - 8080:80

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: toor

  shinyproxy:
    image: shinyproxy
    ports:
      - 8081:8080

  producer:
    image: producer
    depends_on:
      - monitor
    ports:
      - 8000:5000
    volumes:
      - ./producer/pending:/received/

  monitor:
    image: google/cadvisor
    ports:
      - 8001:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
